#!/usr/bin/env bash

COMMAND="$1"
shift

export APP_USER_ID=${APP_USER_ID:-$(id -u)}
export APP_GROUP_ID=${APP_GROUP_ID:-$(id -g)}

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: clean-tmp, reset, install, rights, composer-install, composer-update"
    echo " shell, shellroot"
    exit 1;
fi

case $COMMAND in
    clean-tmp)
        docker exec -t -i rarangi_php appctl.sh clean-tmp;;
    reset)
        docker exec -t -i rarangi_php appctl.sh reset;;
    install)
        docker exec -t -i rarangi_php appctl.sh install;;
    rights)
        docker exec -t -i rarangi_php appctl.sh rights;;
    composer-install)
        docker exec -t -i rarangi_php appctl.sh composer-install;;
    composer-update)
        docker exec -t -i rarangi_php appctl.sh composer-update;;
    #unittests)
    #    docker exec -t -i rarangi_php appctl.sh unittests;;
    shell)
       docker exec -it --user userphp rarangi_php  /bin/bash -l;;
    shellroot)
       docker exec -it rarangi_php  /bin/bash  -l;;
    *)
        echo "wrong command"
        exit 2
        ;;
esac


