#!/usr/bin/env bash

set -e

export APP_USER_ID=${APP_USER_ID:-$(id -u)}
export APP_GROUP_ID=${APP_GROUP_ID:-$(id -g)}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

if [ "$APP_WEB_PORT" == "" ]; then
  export APP_WEB_PORT=8213
fi

docker-compose -p jelix-rarangi-tests $CMD
